docs: create metadata
linz/nz-facilities pull request #4
Opened 2021-06-07 20:43 UTC by jducnuigeen

Fixes: #[243](https://github.com/linz/qgis-buildingsgeneralisation-plugin/issues/243)
Made to be as concise as possible, with the idea the Data Dictionary is more detailed.
Check attribution in the section "Metadata Constraints" since this has more than one attributing source.
Metadata File identifier created from ANZMetLite.

2021-06-08 21:49 UTC, dwsilk commented on metadata/nz_facilities.xml
> +NZ Facilities contains data sourced from NationalMap, Ministry of Education and Ministry of Health licensed for reuse under CC BY 4.0.
NZ Facilities contains data sourced from [NationalMap](https://www.nationalmap.co.nz/), [Ministry of Education](https://www.educationcounts.govt.nz/) and [Ministry of Health](https://www.health.govt.nz/) licensed for reuse under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

2021-06-08 21:54 UTC, dwsilk requested changes

2021-06-08 21:54 UTC, dwsilk commented on metadata/nz_facilities.xml
> +NZ Facilities contains data sourced from NationalMap, Ministry of Education and Ministry of Health licensed for reuse under CC BY 4.0.
Should contain links ^

2021-06-08 21:54 UTC, dwsilk commented on metadata/nz_facilities.xml
> +**Related NZ Facilities data**
Just `**Related data**` ?

2021-06-08 21:54 UTC, dwsilk commented on metadata/nz_facilities.xml
> +NZ Facilities contains data sourced from NationalMap, Ministry of Education and Ministry of Health licensed for reuse under CC BY 4.0.
Same as above.. add links.

2021-06-08 21:54 UTC, dwsilk commented on metadata/nz_facilities.xml
> +• The NAME attribute provides a facility name which has consistent naming convention applied. This name may directly match the name provide by the authoritative source.
provided (fix typo)

2021-06-08 21:54 UTC, dwsilk commented on metadata/nz_facilities.xml
> +• The EXTERNAL_NAME attribute provides the facility name used by the authoritative source.
maybe this should be `source_name` ? probably too late to suggest that and I know that `external` matches the terminology we have used elsewhere..

2021-06-16 02:09 UTC, Douglas-K approved these changes

2021-06-16 02:10 UTC, merged